# NumPy Basics: Arrays and Vectorized Computation

## Chapter 4 in textbook Python in Data Science.

### Introduction to NumPy

Numpy, short for Numerical Python, is one of the most important foundational packages for numerical computing in Python. 

### 4.1 The NumPy ndarray: A Multidimensional Array Object.

One of the key features of NumPy is its N-dimensional array object, or ndarray, which is fast, flexible container for large dataset in Python. Arrays enable you to perform mathematical operations on whole blocks of data using similar syntax to the equivalent operations between scalar elements

In [1]:
import numpy as np

##### Example in first edition

In [2]:
data=np.array([
    [0.9526, -0.246, -0.8856],
    [0.05639, 0.2379, 0.9104]
])

In [3]:
data

array([[ 0.9526 , -0.246  , -0.8856 ],
       [ 0.05639,  0.2379 ,  0.9104 ]])

In [4]:
data*10

array([[ 9.526 , -2.46  , -8.856 ],
       [ 0.5639,  2.379 ,  9.104 ]])

In [5]:
data+data

array([[ 1.9052 , -0.492  , -1.7712 ],
       [ 0.11278,  0.4758 ,  1.8208 ]])

##### Example in second edition

I first generate a small array of random data. `np.random.randn` returns a sample (or samples) from the “standard normal” distribution with dimension 2 rows by 3 columns.

In [6]:
data=np.random.randn(2,3)

In [7]:
data

array([[-0.15869157, -2.01261097,  0.34726453],
       [-0.58757717,  0.55562913, -0.3559897 ]])

I then write mathematical operations with data. In the first example, all of the elements have been multiplied by 10. In the second, the corresponding values in each “cell” in the array have been added to each other.

In [8]:
data*10

array([[ -1.5869157 , -20.12610968,   3.47264529],
       [ -5.87577166,   5.55629129,  -3.55989699]])

In [9]:
data+data

array([[-0.31738314, -4.02522194,  0.69452906],
       [-1.17515433,  1.11125826, -0.7119794 ]])

An ndarray is a generic multidimensional container for <font color=red size=1.5> homogeneous data</font>; that is, all
of the elements must be the same type. Every array has a `shape`, a tuple indicating the
size of each dimension, and a `dtype`, an object describing the data type of the array:

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

#### Section 1: Creating ndarrays

The easiest way to create an `array` is to use the array function. This accepts any
sequence-like object (including other arrays) and produces a new NumPy array containing
the passed data.

In [12]:
data1=[6,7.5,8,0,1]

In [13]:
arr1=np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

Nested sequences, like a list of equal-length lists, will be converted into a multidimensional
array.

In [14]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
arr2.shape

(2, 4)

In [16]:
arr2.ndim

2

In [17]:
arr1.dtype

dtype('float64')

In [18]:
arr2.dtype

dtype('int64')

In addition to `np.array`, there are a number of other functions for creating new
arrays. As examples, `zeros` and `ones` create arrays of 0s or 1s, respectively, with a
given length or shape. `empty` creates an array without initializing its values to any particular
value.

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [23]:
np.empty((2,3,2))

array([[[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [2.00000000e+000, 2.00000000e+000],
        [3.95252517e-323, 5.04621361e+180]]])

`arange` is an array-valued version of the built-in Python `range` function

In [24]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

`eye` and `identity` Create a square $N\times N$ identity matrix. 

* `numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')` N:Number of rows in the output. k:Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal. 
* `numpy.identity(n, dtype=None)` n: Number of rows

In [25]:
np.eye(N=2, dtype=int)

array([[1, 0],
       [0, 1]])

In [26]:
np.eye(N=3, k=1, dtype=int)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [27]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

`zeros_like` and `ones_like()` returns an array of ones with the same shape and type as a given array. `full` produces an array of the given shape and dtype with all values set to the indicated 'filled value' 

In [28]:
x=np.arange(6)
x=x.reshape((2,3))
x

array([[0, 1, 2],
       [3, 4, 5]])

In [29]:
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1]])

In [30]:
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

In [31]:
np.full_like(x, 2)

array([[2, 2, 2],
       [2, 2, 2]])

In [32]:
np.full((2,3), 6)

array([[6, 6, 6],
       [6, 6, 6]])

#### Section 2: Data Types for ndarrays

In [33]:
arr1=np.array([1,2,3], dtype=np.float64)
arr2=np.array([1,2,3], dtype=np.int32)

In [34]:
arr1.dtype

dtype('float64')

In [35]:
arr2.dtype

dtype('int32')

You can explicitly convert or cast an array from one dtype to another using ndarray’s
`astype` method.

In [36]:
arr=np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [37]:
float_arr=arr.astype(np.float64)

In [38]:
float_arr.dtype

dtype('float64')

You can explicitly convert or cast an array from one dtype to another using ndarray’s
astype method.

In [39]:
arr=np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])

In [40]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

If you have an array of strings representing numbers, you can use astype to convert
them to numeric form.

In [41]:
numeric_strings=np.array(['1.25','-9.6','42'], dtype=np.string_)

In [42]:
numeric_strings.astype(np.float64)

array([ 1.25, -9.6 , 42.  ])

In [43]:
int_array=np.arange(10)

In [44]:
calibers=np.array([0.22,.270,.357,.380,.44,.50], dtype=np.float64)

In [45]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### Section 3: Arithmetic with NumPy Arrays

Arrays are important because they enable you to express batch operations on data
without writing any for loops. NumPy users call this `vectorization`.

In [46]:
arr=np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

<font color=red> Any arithmetic
operations between equal-size arrays applies the operation element-wise.</font>

In [47]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [48]:
arr/arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

Arithmetic operations with scalars propagate the scalar argument to each element in
the array. 

In [50]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [51]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

Comparisons between arrays of the same size yield boolean arrays.

In [52]:
arr2=np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [53]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

#### Section 4:  Basic Indexing and Slicing

NumPy array indexing is a rich topic, as there are many ways you may want to select
a subset of your data or individual elements. One-dimensional arrays are simple; on
the surface they act similarly to Python lists.

In [54]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr[5]

5

In [56]:
arr[5:8]

array([5, 6, 7])

In [57]:
arr[5:8]=12

An important first distinction
from Python’s built-in lists is that array slices are views on the original array.
This means that the data is not copied, and any modifications to the view will be
reflected in the source array.

In [58]:
arr_slice=arr[5:8]
arr_slice

array([12, 12, 12])

In [59]:
arr_slice[1]=12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [60]:
arr_slice[:]=64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

* If you want a copy of a slice of an ndarray instead of a view, you
will need to explicitly copy the array—for example,
`arr[5:8].copy()`.
* With higher dimensional arrays, you have many more options. In a two-dimensional array, the elements at each index are no longer scalars but rather one-dimensional arrays

In [61]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
arr2d[2]

array([7, 8, 9])

Thus, individual elements can be accessed recursively. But that is a bit too much
work, so you can pass a comma-separated list of indices to select individual elements.
So these are equivalent.

In [63]:
arr2d[0][2]

3

In [64]:
arr2d[0,2]

3

In multidimensional arrays, if you omit later indices, the returned object will be a
lower dimensional ndarray consisting of all the data along the higher dimensions.

In [65]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]] ])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [66]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
old_values=arr3d[0].copy()

In [68]:
arr3d[0]=42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [69]:
arr3d[0]=old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [70]:
arr3d[1,0]

array([7, 8, 9])

#### Section 5: Indexing with slices

In [90]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

Consider the two-dimensional array from before, arr2d. Slicing this array is a bit
different.

In [91]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Select the first two rows of arr2d

In [92]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

You can pass multiple slices just like you can pass multiple indexes.

In [93]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [94]:
arr2d[1, :2]

array([4, 5])

In [95]:
arr2d[:2,2]

array([3, 6])

Note that a colon by itself means to take the entire
axis, so you can slice only higher dimensional axes by doing.

In [96]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

Assigning to a slice expression assigns to the whole selection.

In [97]:
arr2d[:2, 1:]=0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

#### Section 6: Boolean Indexing

In [98]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [99]:
data=np.random.randn(7,4)
data

array([[-0.38815657,  0.71769701, -1.55387617, -0.11230809],
       [ 0.69543147,  0.93545846, -0.83742954,  0.29292174],
       [-1.22834733,  4.04659558,  0.37414577, -1.04542871],
       [ 0.72307634, -0.43113426,  1.58613742, -0.80342908],
       [ 0.870066  , -0.85035078,  0.422211  , -0.75903617],
       [-0.35871375, -0.37708637, -0.64919835,  1.00451475],
       [ 0.10523587,  0.10849586, -2.04142461, -1.84196259]])

Suppose each name corresponds to a row in the data array and we wanted to select
all the rows with corresponding name 'Bob'. Like arithmetic operations, comparisons
(such as `==`) with arrays are also vectorized. Thus, comparing names with the
string 'Bob' yields a boolean array. <font color=red> The boolean array must be of the same length as the array axis it’s indexing. </font>

In [100]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

This boolean array can be passed when indexing the array.

In [101]:
data[names=='Bob']

array([[-0.38815657,  0.71769701, -1.55387617, -0.11230809],
       [ 0.72307634, -0.43113426,  1.58613742, -0.80342908]])

You can
even mix and match boolean arrays with slices or integers.

In [102]:
data[names=='Bob',2:]

array([[-1.55387617, -0.11230809],
       [ 1.58613742, -0.80342908]])

In [103]:
data[names=='Bob',3]

array([-0.11230809, -0.80342908])

To select everything but 'Bob', you can either use `!=` or negate the condition using `~`.

In [104]:
data[names!='Bob']

array([[ 0.69543147,  0.93545846, -0.83742954,  0.29292174],
       [-1.22834733,  4.04659558,  0.37414577, -1.04542871],
       [ 0.870066  , -0.85035078,  0.422211  , -0.75903617],
       [-0.35871375, -0.37708637, -0.64919835,  1.00451475],
       [ 0.10523587,  0.10849586, -2.04142461, -1.84196259]])

In [105]:
data[~(names=='Bob')]

array([[ 0.69543147,  0.93545846, -0.83742954,  0.29292174],
       [-1.22834733,  4.04659558,  0.37414577, -1.04542871],
       [ 0.870066  , -0.85035078,  0.422211  , -0.75903617],
       [-0.35871375, -0.37708637, -0.64919835,  1.00451475],
       [ 0.10523587,  0.10849586, -2.04142461, -1.84196259]])

The `~` operator can be useful when you want to invert a general condition.

In [106]:
cond=names=='Bob'

In [107]:
data[~cond]

array([[ 0.69543147,  0.93545846, -0.83742954,  0.29292174],
       [-1.22834733,  4.04659558,  0.37414577, -1.04542871],
       [ 0.870066  , -0.85035078,  0.422211  , -0.75903617],
       [-0.35871375, -0.37708637, -0.64919835,  1.00451475],
       [ 0.10523587,  0.10849586, -2.04142461, -1.84196259]])

Selecting two of the three names to combine multiple boolean conditions, use
boolean arithmetic operators like `&` (and) and `|` (or). <font color=red> The Python keywords `and` and `or` do not work with boolean arrays. </font>

In [108]:
mask=(names=='Bob') | (names=='Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [109]:
data[mask]

array([[-0.38815657,  0.71769701, -1.55387617, -0.11230809],
       [-1.22834733,  4.04659558,  0.37414577, -1.04542871],
       [ 0.72307634, -0.43113426,  1.58613742, -0.80342908],
       [ 0.870066  , -0.85035078,  0.422211  , -0.75903617]])

Setting values with boolean arrays works in a common-sense way. To set all of the
negative values in data to 0 we need only do. Setting whole rows or columns using a one-dimensional boolean array is also easy.

In [110]:
data[data<0]=0
data

array([[0.        , 0.71769701, 0.        , 0.        ],
       [0.69543147, 0.93545846, 0.        , 0.29292174],
       [0.        , 4.04659558, 0.37414577, 0.        ],
       [0.72307634, 0.        , 1.58613742, 0.        ],
       [0.870066  , 0.        , 0.422211  , 0.        ],
       [0.        , 0.        , 0.        , 1.00451475],
       [0.10523587, 0.10849586, 0.        , 0.        ]])

In [111]:
data[names!='Joe']=7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.69543147, 0.93545846, 0.        , 0.29292174],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 1.00451475],
       [0.10523587, 0.10849586, 0.        , 0.        ]])

#### Section 7: Fancy Indexing
Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.

In [112]:
arr=np.empty((8,4))
arr

array([[2.00000000e+000, 2.00390505e+000, 1.28457068e-322,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        1.25892564e-047],
       [2.00000000e+000, 2.00000000e+000, 4.30513067e-096,
        6.32299154e+233],
       [3.65588282e+233, 1.74569531e+238, 1.11763132e+261,
        1.16318408e-028],
       [2.24729310e+174, 1.56605686e-076, 4.41847384e-062,
        2.26199886e-076],
       [2.42137576e-052, 2.10468709e-308, 2.00000000e+000,
        2.00000000e+000]])

In [113]:
for i in np.arange(8):
    arr[i]=i

In [114]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

To select out a subset of the rows in a particular order, you can simply pass a list or
ndarray of integers specifying the desired order. Using <font color=red>negative</font> indices selects rows from
the end.

In [115]:
arr[[4,3,2,5]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [2., 2., 2., 2.],
       [5., 5., 5., 5.]])

In [116]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

Passing multiple index arrays does something slightly different; it selects a onedimensional
array of elements corresponding to each tuple of indices. Here the elements (1, 0), (5, 3), (7, 1), and (2, 2) were selected.

In [117]:
arr=np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [119]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [120]:
arr[[1,5,7,2]][:, [0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

#### Section 8: Transposing Arrays and Swapping Axes

In [121]:
arr=np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [122]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

Computing the inner matrix product using `np.dot`.

In [123]:
arr=np.random.randn(6,3)
arr

array([[-0.1256031 ,  0.18774549, -0.54799267],
       [ 0.35126656,  1.26110783,  1.03672562],
       [-0.9352953 ,  1.57796853,  1.06066976],
       [ 2.00113068, -0.10623439, -0.2440111 ],
       [ 0.07339186,  0.68735049,  0.55994147],
       [ 1.09187685,  0.22355252, -0.37558341]])

In [124]:
np.dot(arr.T, arr)

array([[ 6.21604705, -0.97451411, -1.41633661],
       [-0.97451411,  4.64933818,  3.20507894],
       [-1.41633661,  3.20507894,  3.01425507]])

In [125]:
arr=np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [126]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [127]:
arr.transpose((2,1,0))

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

ndarray has the method
`swapaxes`, which takes a pair of axis numbers and switches the indicated axes to rearrange
the data.

In [128]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [129]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

### 4.2 Universal Functions: Fast Element-Wise Array Functions

A universal function, or ufunc, is a function that performs element-wise operations
on data in ndarrays. You can think of them as fast vectorized wrappers for simple
functions that take one or more scalar values and produce one or more scalar results.

In [130]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [132]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [134]:
x=np.random.randn(8)
y=np.random.randn(8)

In [135]:
x

array([ 0.05158201,  1.1953709 , -0.1350737 ,  1.03345676, -0.60963851,
       -0.08521247, -0.99942919,  0.85170169])

In [136]:
y

array([ 0.62740029, -0.03240519,  0.54089252, -2.7593038 , -2.32621549,
       -0.01863068,  0.76462429,  0.84599466])

In [137]:
np.maximum(x,y)

array([ 0.62740029,  1.1953709 ,  0.54089252,  1.03345676, -0.60963851,
       -0.01863068,  0.76462429,  0.85170169])

In [138]:
arr=np.random.randn(7)*5
arr

array([ 0.40709063, -5.96995528,  3.41510159, -1.07157011, -3.30165673,
        4.31166241,  2.35721121])

In [139]:
remainder, whole_part=np.modf(arr)

In [140]:
remainder

array([ 0.40709063, -0.96995528,  0.41510159, -0.07157011, -0.30165673,
        0.31166241,  0.35721121])

In [141]:
whole_part

array([ 0., -5.,  3., -1., -3.,  4.,  2.])

In [72]:
xarr=np.array([1.1,2.2,1.3,1.4,1.5])

In [73]:
yarr=np.array([2,2,3,4,5])

In [74]:
cond=np.array([True, False, True, True, False])

In [75]:
result=[(x if c else y)
       for x, y, c in zip(xarr, yarr, cond)]

In [76]:
result

[1.1, 2, 1.3, 1.4, 5]

In [77]:
result=np.where(cond, xarr, yarr)

In [78]:
result

array([1.1, 2. , 1.3, 1.4, 5. ])

# Introduction to Jupyter Notebook


In [79]:
#arr=np.array([1,2,3])

In [80]:
#arr

In [81]:
#np.mean(arr)

In [82]:
#np.sum(arr)

In [83]:
#%pwd

In [84]:
#import matplotlib.pyplot as plt
#%matplotlib inline

In [85]:
#N = 50
#x = np.random.rand(N)
#y = np.random.rand(N)
#colors = np.random.rand(N)

In [86]:
#area = np.pi *(15*np.random.rand(N))**2 #) to 15 point radiuses

#plt.scatter(x, y, s=area, c=colors, alpha=0.5)

In [87]:
#import sys

In [88]:
#sys.path
#sys.executable

In [89]:
#%%HTML
#<iframe width="815" height="500" src="http://www.lancaster.ac.uk/staff/haleac/malaria/" frameborder="0" allowfullscreen><iframe>